### ISSUE TITLE
Plugin has disappeared from the Lapce Plugin Panel

### ISSUE THREAD

**Issue by ranger-ross** [oknozor/lapce-java#1]
This plugin has seemingly disappeared from the Lapce plugin panel. I think it might have something to do with a recently update in how Lapce sources plugins.

<img width="351" alt="image" src="https://user-images.githubusercontent.com/25847436/201512372-cd4ce0da-a19a-4de8-bd3c-7daadec57b59.png">

**Comment by ranger-ross** [comment]
Possibly related to this: 
https://github.com/lapce/lapce/pull/1643: Use https://plugins.lapce.dev/ as the plugin registry

**Comment by oknozor** [comment]
Hey, thanks for telling me. I just published the plugin to the lapce repository.
